---
version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=692609349536.dkr.ecr.ap-northeast-2.amazonaws.com/dean-example
      - EKS_CLUSTER_NAME=dean-sandbox
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:latest
      - echo Deploy K8s...
      - aws eks update-kubeconfig --region ap-northeast-2 --name $EKS_CLUSTER_NAME
      - kubectl apply -k k8s/dev
      - kubectl rollout restart deploy hello-deployment
