spring:
  datasource:
    url: jdbc-secretsmanager:mariadb://database-2.cluster-cvhx7lz6ywsu.ap-northeast-2.rds.amazonaws.com:3306/test
    username: osb/dev/mysql
    driver-class-name: com.amazonaws.secretsmanager.sql.AWSSecretsManagerMariaDBDriver
  redis:
    ssl: true
    cluster:
      nodes: clustercfg.redis-demo.5p5img.memorydb.ap-northeast-2.amazonaws.com:6379
  kafka:
    producer:
      bootstrap-servers:
        - b-1.dynamo.zrnj19.c2.kafka.ap-northeast-2.amazonaws.com:9092
        - b-2.dynamo.zrnj19.c2.kafka.ap-northeast-2.amazonaws.com:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers:
        - b-1.dynamo.zrnj19.c2.kafka.ap-northeast-2.amazonaws.com:9092
        - b-2.dynamo.zrnj19.c2.kafka.ap-northeast-2.amazonaws.com:9092
      enable-auto-commit: false
    listener:
      ack-mode: record
