apiVersion: batch/v1
kind: Job
metadata:
  name: badge-fill-job-2
spec:
  template:
    spec:
      serviceAccountName: osb-service-account
      containers:
        - name:  badge-fill-job-2
          image: 692609349536.dkr.ecr.ap-northeast-2.amazonaws.com/dynamodb-example:latest
          command: ["java", "-jar", "-Xmx1g", "-Xms1g", "-server", "build/libs/dynamodb-example-1.0-SNAPSHOT.jar"]
          args:
            - badgeFillJob
          resources:
            requests:
              cpu: 1
              memory: 1.5G
            limits:
              cpu: 1
              memory: 1.5G
          env:
            - name: TZ
              value: "Asia/Seoul"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
      restartPolicy: Never
